image:
  repository: gcr.io/forgerock-io/ds
  #repository: gcr.io/engineering-devops/ds
  tag: 6.5.2
  pullPolicy: Always

gcs:
  enabled: false
  bucket: gs://forgeops/dj-backup/s-cluster

s3:
  enabled: false
  bucket: s3://forgeops/dj-backup/s-cluster  

nfs:
  server: fs-0b6822c0.efs.eu-west-1.amazonaws.com
  path: /export

backup:
  pvcName: ds-backup
  storageSize: 100Gi

createPVC: true

slackUrl: undefined
