namespace: prod
resources:
- ../../../base/kustomizeConfig
- ../../../base/forgeops-secrets
- ../../../base/postgres
- ../../../base/6.5/ds/cts
- ../../../base/6.5/ds/idrepo
- ../../../base/am
- ../../../base/amster
- ../../../base/idm
- ../../../base/ingress

configMapGenerator:
- name: platform-config
  # The env vars below can be passed into a pod using the envFrom pod spec.
  # These global variables can be used to parameterize your deployments.
  # The FQDN and URLs here should match your ingress or istio gateway definitions
  literals:
  - FQDN=$(NAMESPACE).iam.fr.kcom.com
  - SUBDOMAIN=iam
  - DOMAIN=fr.kcom.com
  - AM_URL=https://$(NAMESPACE).iam.fr.kcom.com/am
  - IDM_ADMIN_URL=https://$(NAMESPACE).iam.fr.kcom.com/admin
  - IDM_REST_URL=https://$(NAMESPACE).iam.fr.kcom.com/openidm
  - CTS_STORES=ds-cts-0.ds-cts:1389

# The variables defined below can be referenced in resources using the syntax $(VARIABLE)
vars:
- name: DOMAIN
  fieldref:
    fieldpath: data.DOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
- name: SUBDOMAIN
  fieldref:
    fieldpath: data.SUBDOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
  fieldref:
    fieldpath: metadata.namespace

